import {
  pgTable,
  uuid,
  varchar,
  text,
  integer,
  numeric,
  doublePrecision,
  boolean,
  jsonb,
  timestamp,
} from "drizzle-orm/pg-core";

export const properties = pgTable("properties", {
  id: uuid("id").defaultRandom().primaryKey(),
  slug: varchar("slug", { length: 100 }).notNull().unique(),
  name: varchar("name", { length: 255 }).notNull(),
  tagline: varchar("tagline", { length: 255 }),
  description: text("description"),
  moreDetails: text("more_details"),
  maxGuests: integer("max_guests").notNull(),
  bedrooms: integer("bedrooms").notNull(),
  bathrooms: doublePrecision("bathrooms").notNull(),
  beds: jsonb("beds").$type<string[]>().default([]),
  cleaningFee: integer("cleaning_fee").notNull().default(0),
  nightlyRate: integer("nightly_rate").notNull().default(0),
  petFee: integer("pet_fee").notNull().default(0),
  maxPets: integer("max_pets").notNull().default(0),
  minStay: integer("min_stay").notNull().default(1),
  checkInTime: varchar("check_in_time", { length: 10 }).default("16:00"),
  checkOutTime: varchar("check_out_time", { length: 10 }).default("11:00"),
  houseRules: text("house_rules"),
  address: text("address"),
  latitude: numeric("latitude", { precision: 10, scale: 7 }),
  longitude: numeric("longitude", { precision: 10, scale: 7 }),
  amenities: jsonb("amenities").$type<string[]>().default([]),
  highlight: varchar("highlight", { length: 255 }),
  isActive: boolean("is_active").notNull().default(true),
  createdAt: timestamp("created_at").defaultNow().notNull(),
  updatedAt: timestamp("updated_at").defaultNow().notNull(),
});
