/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AdminRouteRouteImport } from './routes/_admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PropertiesIndexRouteImport } from './routes/properties/index'
import { Route as PropertiesPropertyIdRouteImport } from './routes/properties/$propertyId'
import { Route as BookingPropertyIdRouteImport } from './routes/booking/$propertyId'
import { Route as AuthVerifyRouteImport } from './routes/auth/verify'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AdminThermostatRouteImport } from './routes/_admin/thermostat'
import { Route as AdminReviewsRouteImport } from './routes/_admin/reviews'
import { Route as AdminDashboardRouteImport } from './routes/_admin/dashboard'
import { Route as AdminCalendarSyncRouteImport } from './routes/_admin/calendar-sync'
import { Route as AdminCalendarRouteImport } from './routes/_admin/calendar'
import { Route as AdminBookingsRouteImport } from './routes/_admin/bookings'
import { Route as AdminChecklistsIndexRouteImport } from './routes/_admin/checklists/index'
import { Route as BookingConfirmationBookingIdRouteImport } from './routes/booking/confirmation.$bookingId'
import { Route as AdminChecklistsChecklistIdRouteImport } from './routes/_admin/checklists/$checklistId'

const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertiesIndexRoute = PropertiesIndexRouteImport.update({
  id: '/properties/',
  path: '/properties/',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertiesPropertyIdRoute = PropertiesPropertyIdRouteImport.update({
  id: '/properties/$propertyId',
  path: '/properties/$propertyId',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingPropertyIdRoute = BookingPropertyIdRouteImport.update({
  id: '/booking/$propertyId',
  path: '/booking/$propertyId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthVerifyRoute = AuthVerifyRouteImport.update({
  id: '/auth/verify',
  path: '/auth/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminThermostatRoute = AdminThermostatRouteImport.update({
  id: '/thermostat',
  path: '/thermostat',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminReviewsRoute = AdminReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCalendarSyncRoute = AdminCalendarSyncRouteImport.update({
  id: '/calendar-sync',
  path: '/calendar-sync',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCalendarRoute = AdminCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminBookingsRoute = AdminBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminChecklistsIndexRoute = AdminChecklistsIndexRouteImport.update({
  id: '/checklists/',
  path: '/checklists/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const BookingConfirmationBookingIdRoute =
  BookingConfirmationBookingIdRouteImport.update({
    id: '/booking/confirmation/$bookingId',
    path: '/booking/confirmation/$bookingId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminChecklistsChecklistIdRoute =
  AdminChecklistsChecklistIdRouteImport.update({
    id: '/checklists/$checklistId',
    path: '/checklists/$checklistId',
    getParentRoute: () => AdminRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/bookings': typeof AdminBookingsRoute
  '/calendar': typeof AdminCalendarRoute
  '/calendar-sync': typeof AdminCalendarSyncRoute
  '/dashboard': typeof AdminDashboardRoute
  '/reviews': typeof AdminReviewsRoute
  '/thermostat': typeof AdminThermostatRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/booking/$propertyId': typeof BookingPropertyIdRoute
  '/properties/$propertyId': typeof PropertiesPropertyIdRoute
  '/properties/': typeof PropertiesIndexRoute
  '/checklists/$checklistId': typeof AdminChecklistsChecklistIdRoute
  '/booking/confirmation/$bookingId': typeof BookingConfirmationBookingIdRoute
  '/checklists/': typeof AdminChecklistsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/bookings': typeof AdminBookingsRoute
  '/calendar': typeof AdminCalendarRoute
  '/calendar-sync': typeof AdminCalendarSyncRoute
  '/dashboard': typeof AdminDashboardRoute
  '/reviews': typeof AdminReviewsRoute
  '/thermostat': typeof AdminThermostatRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/booking/$propertyId': typeof BookingPropertyIdRoute
  '/properties/$propertyId': typeof PropertiesPropertyIdRoute
  '/properties': typeof PropertiesIndexRoute
  '/checklists/$checklistId': typeof AdminChecklistsChecklistIdRoute
  '/booking/confirmation/$bookingId': typeof BookingConfirmationBookingIdRoute
  '/checklists': typeof AdminChecklistsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_admin': typeof AdminRouteRouteWithChildren
  '/account': typeof AccountRoute
  '/_admin/bookings': typeof AdminBookingsRoute
  '/_admin/calendar': typeof AdminCalendarRoute
  '/_admin/calendar-sync': typeof AdminCalendarSyncRoute
  '/_admin/dashboard': typeof AdminDashboardRoute
  '/_admin/reviews': typeof AdminReviewsRoute
  '/_admin/thermostat': typeof AdminThermostatRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/booking/$propertyId': typeof BookingPropertyIdRoute
  '/properties/$propertyId': typeof PropertiesPropertyIdRoute
  '/properties/': typeof PropertiesIndexRoute
  '/_admin/checklists/$checklistId': typeof AdminChecklistsChecklistIdRoute
  '/booking/confirmation/$bookingId': typeof BookingConfirmationBookingIdRoute
  '/_admin/checklists/': typeof AdminChecklistsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/bookings'
    | '/calendar'
    | '/calendar-sync'
    | '/dashboard'
    | '/reviews'
    | '/thermostat'
    | '/auth/login'
    | '/auth/verify'
    | '/booking/$propertyId'
    | '/properties/$propertyId'
    | '/properties/'
    | '/checklists/$checklistId'
    | '/booking/confirmation/$bookingId'
    | '/checklists/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/bookings'
    | '/calendar'
    | '/calendar-sync'
    | '/dashboard'
    | '/reviews'
    | '/thermostat'
    | '/auth/login'
    | '/auth/verify'
    | '/booking/$propertyId'
    | '/properties/$propertyId'
    | '/properties'
    | '/checklists/$checklistId'
    | '/booking/confirmation/$bookingId'
    | '/checklists'
  id:
    | '__root__'
    | '/'
    | '/_admin'
    | '/account'
    | '/_admin/bookings'
    | '/_admin/calendar'
    | '/_admin/calendar-sync'
    | '/_admin/dashboard'
    | '/_admin/reviews'
    | '/_admin/thermostat'
    | '/auth/login'
    | '/auth/verify'
    | '/booking/$propertyId'
    | '/properties/$propertyId'
    | '/properties/'
    | '/_admin/checklists/$checklistId'
    | '/booking/confirmation/$bookingId'
    | '/_admin/checklists/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  AccountRoute: typeof AccountRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthVerifyRoute: typeof AuthVerifyRoute
  BookingPropertyIdRoute: typeof BookingPropertyIdRoute
  PropertiesPropertyIdRoute: typeof PropertiesPropertyIdRoute
  PropertiesIndexRoute: typeof PropertiesIndexRoute
  BookingConfirmationBookingIdRoute: typeof BookingConfirmationBookingIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/properties/': {
      id: '/properties/'
      path: '/properties'
      fullPath: '/properties/'
      preLoaderRoute: typeof PropertiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/properties/$propertyId': {
      id: '/properties/$propertyId'
      path: '/properties/$propertyId'
      fullPath: '/properties/$propertyId'
      preLoaderRoute: typeof PropertiesPropertyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking/$propertyId': {
      id: '/booking/$propertyId'
      path: '/booking/$propertyId'
      fullPath: '/booking/$propertyId'
      preLoaderRoute: typeof BookingPropertyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/verify': {
      id: '/auth/verify'
      path: '/auth/verify'
      fullPath: '/auth/verify'
      preLoaderRoute: typeof AuthVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/thermostat': {
      id: '/_admin/thermostat'
      path: '/thermostat'
      fullPath: '/thermostat'
      preLoaderRoute: typeof AdminThermostatRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/reviews': {
      id: '/_admin/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof AdminReviewsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/dashboard': {
      id: '/_admin/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/calendar-sync': {
      id: '/_admin/calendar-sync'
      path: '/calendar-sync'
      fullPath: '/calendar-sync'
      preLoaderRoute: typeof AdminCalendarSyncRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/calendar': {
      id: '/_admin/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AdminCalendarRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/bookings': {
      id: '/_admin/bookings'
      path: '/bookings'
      fullPath: '/bookings'
      preLoaderRoute: typeof AdminBookingsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/checklists/': {
      id: '/_admin/checklists/'
      path: '/checklists'
      fullPath: '/checklists/'
      preLoaderRoute: typeof AdminChecklistsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/booking/confirmation/$bookingId': {
      id: '/booking/confirmation/$bookingId'
      path: '/booking/confirmation/$bookingId'
      fullPath: '/booking/confirmation/$bookingId'
      preLoaderRoute: typeof BookingConfirmationBookingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/checklists/$checklistId': {
      id: '/_admin/checklists/$checklistId'
      path: '/checklists/$checklistId'
      fullPath: '/checklists/$checklistId'
      preLoaderRoute: typeof AdminChecklistsChecklistIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminBookingsRoute: typeof AdminBookingsRoute
  AdminCalendarRoute: typeof AdminCalendarRoute
  AdminCalendarSyncRoute: typeof AdminCalendarSyncRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminReviewsRoute: typeof AdminReviewsRoute
  AdminThermostatRoute: typeof AdminThermostatRoute
  AdminChecklistsChecklistIdRoute: typeof AdminChecklistsChecklistIdRoute
  AdminChecklistsIndexRoute: typeof AdminChecklistsIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminBookingsRoute: AdminBookingsRoute,
  AdminCalendarRoute: AdminCalendarRoute,
  AdminCalendarSyncRoute: AdminCalendarSyncRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminReviewsRoute: AdminReviewsRoute,
  AdminThermostatRoute: AdminThermostatRoute,
  AdminChecklistsChecklistIdRoute: AdminChecklistsChecklistIdRoute,
  AdminChecklistsIndexRoute: AdminChecklistsIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  AccountRoute: AccountRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthVerifyRoute: AuthVerifyRoute,
  BookingPropertyIdRoute: BookingPropertyIdRoute,
  PropertiesPropertyIdRoute: PropertiesPropertyIdRoute,
  PropertiesIndexRoute: PropertiesIndexRoute,
  BookingConfirmationBookingIdRoute: BookingConfirmationBookingIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
