/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PropertiesIndexRouteImport } from './routes/properties/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as PropertiesPropertyIdRouteImport } from './routes/properties/$propertyId'
import { Route as BookingPropertyIdRouteImport } from './routes/booking/$propertyId'
import { Route as AuthVerifyRouteImport } from './routes/auth/verify'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as ApiDebugRouteImport } from './routes/api/debug'
import { Route as AdminThermostatRouteImport } from './routes/admin/thermostat'
import { Route as AdminTestUploadRouteImport } from './routes/admin/test-upload'
import { Route as AdminReviewsRouteImport } from './routes/admin/reviews'
import { Route as AdminInspectionsRouteImport } from './routes/admin/inspections'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'
import { Route as AdminCalendarSyncRouteImport } from './routes/admin/calendar-sync'
import { Route as AdminCalendarRouteImport } from './routes/admin/calendar'
import { Route as AdminBookingsRouteImport } from './routes/admin/bookings'
import { Route as InspectTokenIndexRouteImport } from './routes/inspect/$token/index'
import { Route as AdminListingsIndexRouteImport } from './routes/admin/listings/index'
import { Route as AdminChecklistsIndexRouteImport } from './routes/admin/checklists/index'
import { Route as InspectCompleteTokenRouteImport } from './routes/inspect/complete.$token'
import { Route as InspectTokenRoomRouteImport } from './routes/inspect/$token/$room'
import { Route as BookingConfirmationBookingIdRouteImport } from './routes/booking/confirmation.$bookingId'
import { Route as AdminListingsNewRouteImport } from './routes/admin/listings/new'
import { Route as AdminListingsSlugRouteImport } from './routes/admin/listings/$slug'
import { Route as AdminInspectionsInspectionIdRouteImport } from './routes/admin/inspections/$inspectionId'
import { Route as AdminChecklistsChecklistIdRouteImport } from './routes/admin/checklists/$checklistId'

const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertiesIndexRoute = PropertiesIndexRouteImport.update({
  id: '/properties/',
  path: '/properties/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const PropertiesPropertyIdRoute = PropertiesPropertyIdRouteImport.update({
  id: '/properties/$propertyId',
  path: '/properties/$propertyId',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingPropertyIdRoute = BookingPropertyIdRouteImport.update({
  id: '/booking/$propertyId',
  path: '/booking/$propertyId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthVerifyRoute = AuthVerifyRouteImport.update({
  id: '/auth/verify',
  path: '/auth/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDebugRoute = ApiDebugRouteImport.update({
  id: '/api/debug',
  path: '/api/debug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminThermostatRoute = AdminThermostatRouteImport.update({
  id: '/thermostat',
  path: '/thermostat',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminTestUploadRoute = AdminTestUploadRouteImport.update({
  id: '/test-upload',
  path: '/test-upload',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminReviewsRoute = AdminReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminInspectionsRoute = AdminInspectionsRouteImport.update({
  id: '/inspections',
  path: '/inspections',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCalendarSyncRoute = AdminCalendarSyncRouteImport.update({
  id: '/calendar-sync',
  path: '/calendar-sync',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCalendarRoute = AdminCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminBookingsRoute = AdminBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => AdminRouteRoute,
} as any)
const InspectTokenIndexRoute = InspectTokenIndexRouteImport.update({
  id: '/inspect/$token/',
  path: '/inspect/$token/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminListingsIndexRoute = AdminListingsIndexRouteImport.update({
  id: '/listings/',
  path: '/listings/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminChecklistsIndexRoute = AdminChecklistsIndexRouteImport.update({
  id: '/checklists/',
  path: '/checklists/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const InspectCompleteTokenRoute = InspectCompleteTokenRouteImport.update({
  id: '/inspect/complete/$token',
  path: '/inspect/complete/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const InspectTokenRoomRoute = InspectTokenRoomRouteImport.update({
  id: '/inspect/$token/$room',
  path: '/inspect/$token/$room',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingConfirmationBookingIdRoute =
  BookingConfirmationBookingIdRouteImport.update({
    id: '/booking/confirmation/$bookingId',
    path: '/booking/confirmation/$bookingId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminListingsNewRoute = AdminListingsNewRouteImport.update({
  id: '/listings/new',
  path: '/listings/new',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminListingsSlugRoute = AdminListingsSlugRouteImport.update({
  id: '/listings/$slug',
  path: '/listings/$slug',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminInspectionsInspectionIdRoute =
  AdminInspectionsInspectionIdRouteImport.update({
    id: '/$inspectionId',
    path: '/$inspectionId',
    getParentRoute: () => AdminInspectionsRoute,
  } as any)
const AdminChecklistsChecklistIdRoute =
  AdminChecklistsChecklistIdRouteImport.update({
    id: '/checklists/$checklistId',
    path: '/checklists/$checklistId',
    getParentRoute: () => AdminRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/account': typeof AccountRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/calendar': typeof AdminCalendarRoute
  '/admin/calendar-sync': typeof AdminCalendarSyncRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/inspections': typeof AdminInspectionsRouteWithChildren
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/test-upload': typeof AdminTestUploadRoute
  '/admin/thermostat': typeof AdminThermostatRoute
  '/api/debug': typeof ApiDebugRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/booking/$propertyId': typeof BookingPropertyIdRoute
  '/properties/$propertyId': typeof PropertiesPropertyIdRoute
  '/admin/': typeof AdminIndexRoute
  '/properties/': typeof PropertiesIndexRoute
  '/admin/checklists/$checklistId': typeof AdminChecklistsChecklistIdRoute
  '/admin/inspections/$inspectionId': typeof AdminInspectionsInspectionIdRoute
  '/admin/listings/$slug': typeof AdminListingsSlugRoute
  '/admin/listings/new': typeof AdminListingsNewRoute
  '/booking/confirmation/$bookingId': typeof BookingConfirmationBookingIdRoute
  '/inspect/$token/$room': typeof InspectTokenRoomRoute
  '/inspect/complete/$token': typeof InspectCompleteTokenRoute
  '/admin/checklists/': typeof AdminChecklistsIndexRoute
  '/admin/listings/': typeof AdminListingsIndexRoute
  '/inspect/$token/': typeof InspectTokenIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/calendar': typeof AdminCalendarRoute
  '/admin/calendar-sync': typeof AdminCalendarSyncRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/inspections': typeof AdminInspectionsRouteWithChildren
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/test-upload': typeof AdminTestUploadRoute
  '/admin/thermostat': typeof AdminThermostatRoute
  '/api/debug': typeof ApiDebugRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/booking/$propertyId': typeof BookingPropertyIdRoute
  '/properties/$propertyId': typeof PropertiesPropertyIdRoute
  '/admin': typeof AdminIndexRoute
  '/properties': typeof PropertiesIndexRoute
  '/admin/checklists/$checklistId': typeof AdminChecklistsChecklistIdRoute
  '/admin/inspections/$inspectionId': typeof AdminInspectionsInspectionIdRoute
  '/admin/listings/$slug': typeof AdminListingsSlugRoute
  '/admin/listings/new': typeof AdminListingsNewRoute
  '/booking/confirmation/$bookingId': typeof BookingConfirmationBookingIdRoute
  '/inspect/$token/$room': typeof InspectTokenRoomRoute
  '/inspect/complete/$token': typeof InspectCompleteTokenRoute
  '/admin/checklists': typeof AdminChecklistsIndexRoute
  '/admin/listings': typeof AdminListingsIndexRoute
  '/inspect/$token': typeof InspectTokenIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/account': typeof AccountRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/calendar': typeof AdminCalendarRoute
  '/admin/calendar-sync': typeof AdminCalendarSyncRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/inspections': typeof AdminInspectionsRouteWithChildren
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/test-upload': typeof AdminTestUploadRoute
  '/admin/thermostat': typeof AdminThermostatRoute
  '/api/debug': typeof ApiDebugRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/booking/$propertyId': typeof BookingPropertyIdRoute
  '/properties/$propertyId': typeof PropertiesPropertyIdRoute
  '/admin/': typeof AdminIndexRoute
  '/properties/': typeof PropertiesIndexRoute
  '/admin/checklists/$checklistId': typeof AdminChecklistsChecklistIdRoute
  '/admin/inspections/$inspectionId': typeof AdminInspectionsInspectionIdRoute
  '/admin/listings/$slug': typeof AdminListingsSlugRoute
  '/admin/listings/new': typeof AdminListingsNewRoute
  '/booking/confirmation/$bookingId': typeof BookingConfirmationBookingIdRoute
  '/inspect/$token/$room': typeof InspectTokenRoomRoute
  '/inspect/complete/$token': typeof InspectCompleteTokenRoute
  '/admin/checklists/': typeof AdminChecklistsIndexRoute
  '/admin/listings/': typeof AdminListingsIndexRoute
  '/inspect/$token/': typeof InspectTokenIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/account'
    | '/admin/bookings'
    | '/admin/calendar'
    | '/admin/calendar-sync'
    | '/admin/dashboard'
    | '/admin/inspections'
    | '/admin/reviews'
    | '/admin/test-upload'
    | '/admin/thermostat'
    | '/api/debug'
    | '/auth/login'
    | '/auth/verify'
    | '/booking/$propertyId'
    | '/properties/$propertyId'
    | '/admin/'
    | '/properties/'
    | '/admin/checklists/$checklistId'
    | '/admin/inspections/$inspectionId'
    | '/admin/listings/$slug'
    | '/admin/listings/new'
    | '/booking/confirmation/$bookingId'
    | '/inspect/$token/$room'
    | '/inspect/complete/$token'
    | '/admin/checklists/'
    | '/admin/listings/'
    | '/inspect/$token/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/admin/bookings'
    | '/admin/calendar'
    | '/admin/calendar-sync'
    | '/admin/dashboard'
    | '/admin/inspections'
    | '/admin/reviews'
    | '/admin/test-upload'
    | '/admin/thermostat'
    | '/api/debug'
    | '/auth/login'
    | '/auth/verify'
    | '/booking/$propertyId'
    | '/properties/$propertyId'
    | '/admin'
    | '/properties'
    | '/admin/checklists/$checklistId'
    | '/admin/inspections/$inspectionId'
    | '/admin/listings/$slug'
    | '/admin/listings/new'
    | '/booking/confirmation/$bookingId'
    | '/inspect/$token/$room'
    | '/inspect/complete/$token'
    | '/admin/checklists'
    | '/admin/listings'
    | '/inspect/$token'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/account'
    | '/admin/bookings'
    | '/admin/calendar'
    | '/admin/calendar-sync'
    | '/admin/dashboard'
    | '/admin/inspections'
    | '/admin/reviews'
    | '/admin/test-upload'
    | '/admin/thermostat'
    | '/api/debug'
    | '/auth/login'
    | '/auth/verify'
    | '/booking/$propertyId'
    | '/properties/$propertyId'
    | '/admin/'
    | '/properties/'
    | '/admin/checklists/$checklistId'
    | '/admin/inspections/$inspectionId'
    | '/admin/listings/$slug'
    | '/admin/listings/new'
    | '/booking/confirmation/$bookingId'
    | '/inspect/$token/$room'
    | '/inspect/complete/$token'
    | '/admin/checklists/'
    | '/admin/listings/'
    | '/inspect/$token/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  AccountRoute: typeof AccountRoute
  ApiDebugRoute: typeof ApiDebugRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthVerifyRoute: typeof AuthVerifyRoute
  BookingPropertyIdRoute: typeof BookingPropertyIdRoute
  PropertiesPropertyIdRoute: typeof PropertiesPropertyIdRoute
  PropertiesIndexRoute: typeof PropertiesIndexRoute
  BookingConfirmationBookingIdRoute: typeof BookingConfirmationBookingIdRoute
  InspectTokenRoomRoute: typeof InspectTokenRoomRoute
  InspectCompleteTokenRoute: typeof InspectCompleteTokenRoute
  InspectTokenIndexRoute: typeof InspectTokenIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/properties/': {
      id: '/properties/'
      path: '/properties'
      fullPath: '/properties/'
      preLoaderRoute: typeof PropertiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/properties/$propertyId': {
      id: '/properties/$propertyId'
      path: '/properties/$propertyId'
      fullPath: '/properties/$propertyId'
      preLoaderRoute: typeof PropertiesPropertyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking/$propertyId': {
      id: '/booking/$propertyId'
      path: '/booking/$propertyId'
      fullPath: '/booking/$propertyId'
      preLoaderRoute: typeof BookingPropertyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/verify': {
      id: '/auth/verify'
      path: '/auth/verify'
      fullPath: '/auth/verify'
      preLoaderRoute: typeof AuthVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/debug': {
      id: '/api/debug'
      path: '/api/debug'
      fullPath: '/api/debug'
      preLoaderRoute: typeof ApiDebugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/thermostat': {
      id: '/admin/thermostat'
      path: '/thermostat'
      fullPath: '/admin/thermostat'
      preLoaderRoute: typeof AdminThermostatRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/test-upload': {
      id: '/admin/test-upload'
      path: '/test-upload'
      fullPath: '/admin/test-upload'
      preLoaderRoute: typeof AdminTestUploadRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/reviews': {
      id: '/admin/reviews'
      path: '/reviews'
      fullPath: '/admin/reviews'
      preLoaderRoute: typeof AdminReviewsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/inspections': {
      id: '/admin/inspections'
      path: '/inspections'
      fullPath: '/admin/inspections'
      preLoaderRoute: typeof AdminInspectionsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/calendar-sync': {
      id: '/admin/calendar-sync'
      path: '/calendar-sync'
      fullPath: '/admin/calendar-sync'
      preLoaderRoute: typeof AdminCalendarSyncRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/calendar': {
      id: '/admin/calendar'
      path: '/calendar'
      fullPath: '/admin/calendar'
      preLoaderRoute: typeof AdminCalendarRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/bookings': {
      id: '/admin/bookings'
      path: '/bookings'
      fullPath: '/admin/bookings'
      preLoaderRoute: typeof AdminBookingsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/inspect/$token/': {
      id: '/inspect/$token/'
      path: '/inspect/$token'
      fullPath: '/inspect/$token/'
      preLoaderRoute: typeof InspectTokenIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/listings/': {
      id: '/admin/listings/'
      path: '/listings'
      fullPath: '/admin/listings/'
      preLoaderRoute: typeof AdminListingsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/checklists/': {
      id: '/admin/checklists/'
      path: '/checklists'
      fullPath: '/admin/checklists/'
      preLoaderRoute: typeof AdminChecklistsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/inspect/complete/$token': {
      id: '/inspect/complete/$token'
      path: '/inspect/complete/$token'
      fullPath: '/inspect/complete/$token'
      preLoaderRoute: typeof InspectCompleteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inspect/$token/$room': {
      id: '/inspect/$token/$room'
      path: '/inspect/$token/$room'
      fullPath: '/inspect/$token/$room'
      preLoaderRoute: typeof InspectTokenRoomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking/confirmation/$bookingId': {
      id: '/booking/confirmation/$bookingId'
      path: '/booking/confirmation/$bookingId'
      fullPath: '/booking/confirmation/$bookingId'
      preLoaderRoute: typeof BookingConfirmationBookingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/listings/new': {
      id: '/admin/listings/new'
      path: '/listings/new'
      fullPath: '/admin/listings/new'
      preLoaderRoute: typeof AdminListingsNewRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/listings/$slug': {
      id: '/admin/listings/$slug'
      path: '/listings/$slug'
      fullPath: '/admin/listings/$slug'
      preLoaderRoute: typeof AdminListingsSlugRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/inspections/$inspectionId': {
      id: '/admin/inspections/$inspectionId'
      path: '/$inspectionId'
      fullPath: '/admin/inspections/$inspectionId'
      preLoaderRoute: typeof AdminInspectionsInspectionIdRouteImport
      parentRoute: typeof AdminInspectionsRoute
    }
    '/admin/checklists/$checklistId': {
      id: '/admin/checklists/$checklistId'
      path: '/checklists/$checklistId'
      fullPath: '/admin/checklists/$checklistId'
      preLoaderRoute: typeof AdminChecklistsChecklistIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
  }
}

interface AdminInspectionsRouteChildren {
  AdminInspectionsInspectionIdRoute: typeof AdminInspectionsInspectionIdRoute
}

const AdminInspectionsRouteChildren: AdminInspectionsRouteChildren = {
  AdminInspectionsInspectionIdRoute: AdminInspectionsInspectionIdRoute,
}

const AdminInspectionsRouteWithChildren =
  AdminInspectionsRoute._addFileChildren(AdminInspectionsRouteChildren)

interface AdminRouteRouteChildren {
  AdminBookingsRoute: typeof AdminBookingsRoute
  AdminCalendarRoute: typeof AdminCalendarRoute
  AdminCalendarSyncRoute: typeof AdminCalendarSyncRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminInspectionsRoute: typeof AdminInspectionsRouteWithChildren
  AdminReviewsRoute: typeof AdminReviewsRoute
  AdminTestUploadRoute: typeof AdminTestUploadRoute
  AdminThermostatRoute: typeof AdminThermostatRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminChecklistsChecklistIdRoute: typeof AdminChecklistsChecklistIdRoute
  AdminListingsSlugRoute: typeof AdminListingsSlugRoute
  AdminListingsNewRoute: typeof AdminListingsNewRoute
  AdminChecklistsIndexRoute: typeof AdminChecklistsIndexRoute
  AdminListingsIndexRoute: typeof AdminListingsIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminBookingsRoute: AdminBookingsRoute,
  AdminCalendarRoute: AdminCalendarRoute,
  AdminCalendarSyncRoute: AdminCalendarSyncRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminInspectionsRoute: AdminInspectionsRouteWithChildren,
  AdminReviewsRoute: AdminReviewsRoute,
  AdminTestUploadRoute: AdminTestUploadRoute,
  AdminThermostatRoute: AdminThermostatRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminChecklistsChecklistIdRoute: AdminChecklistsChecklistIdRoute,
  AdminListingsSlugRoute: AdminListingsSlugRoute,
  AdminListingsNewRoute: AdminListingsNewRoute,
  AdminChecklistsIndexRoute: AdminChecklistsIndexRoute,
  AdminListingsIndexRoute: AdminListingsIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  AccountRoute: AccountRoute,
  ApiDebugRoute: ApiDebugRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthVerifyRoute: AuthVerifyRoute,
  BookingPropertyIdRoute: BookingPropertyIdRoute,
  PropertiesPropertyIdRoute: PropertiesPropertyIdRoute,
  PropertiesIndexRoute: PropertiesIndexRoute,
  BookingConfirmationBookingIdRoute: BookingConfirmationBookingIdRoute,
  InspectTokenRoomRoute: InspectTokenRoomRoute,
  InspectCompleteTokenRoute: InspectCompleteTokenRoute,
  InspectTokenIndexRoute: InspectTokenIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
